### ISSUE TITLE
Passing in className as options parameter with the addMarker method

### ISSUE THREAD

**Issue by alan-wu** [AnatomicMaps/flatmap-viewer#16]
It will be great to allow className to be passed through into maplibreGL's addMarker method which will allow developers to fine tune the marker styles.

Details on available mark options on MapLibreGL can be found here - https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.MarkerOptions/

**Comment by dbrnz** [comment]
Now in @abi-software/flatmap-viewer@2.4.2-b.5
