### ISSUE TITLE
Error with calling resetMap

### ISSUE THREAD

**Issue by alan-wu** [AnatomicMaps/flatmap-viewer#19]
I receive an error saying `this.__enablePathFeatures is not a function` after calling the `resetMap` function on flatmap-viewer.

The call stacks:

```
Uncaught TypeError: this.__enablePathFeatures is not a function
    at UserInteractions.reset
    at FlatMap.resetMap
```

**Comment by dbrnz** [comment]
What version of the viewer is this happening on?

**Comment by alan-wu** [comment]
> What version of the viewer is this happening on?

Version 2.4.4

**Comment by dbrnz** [comment]
It looks as if that line of code should have been removed as part of commit 3e2dbcd...

Consider it gone!
