### ISSUE TITLE
Feature request: External API for highlighting on species

### ISSUE THREAD

**Issue by Tehsurfer** [AnatomicMaps/flatmap-viewer#20]
Currently there is an api for visibility based on a selected species:

`mapImp.enableConnectivityByTaxonIds(payload.key, payload.value)`

Which can be seen used in action in the image below:

![image (16)](https://github.com/AnatomicMaps/flatmap-viewer/assets/37255664/06deb011-b307-459a-9e6e-87f692769421)

I would like an external api that does the same thing, but highlights the connectivity based on a selected species.

similar to `mapImp.zoomToFeatures(toHighlight, { noZoomIn: true })`, but with a species as input as opposed to a path

**Comment by dbrnz** [comment]
Resolved in @abi-software/flatmap-viewer@2.5.3.

See [FlatMap.taxonIdentifiers](https://flatmap-viewer.readthedocs.io/en/mapmaker-v2/API.html#FlatMap.taxonIdentifiers), [FlatMap.selectGeoJSONFeatures](https://flatmap-viewer.readthedocs.io/en/mapmaker-v2/API.html#FlatMap.selectGeoJSONFeatures) and [FlatMap.zoomToGeoJSONFeatures](https://flatmap-viewer.readthedocs.io/en/mapmaker-v2/API.html#FlatMap.zoomToGeoJSONFeatures).
