### ISSUE TITLE
Add marker does not work in anatomical maps with Vagus

### ISSUE THREAD

**Issue by alan-wu** [AnatomicMaps/flatmap-viewer#24]
Marker does not get created and displayed with the following when the feature is set to UBERON:0001759 but this is not an issue when the feature is heart (UBERON:0000948) or other features.

flatmap.addMarker(feature, {element: wrapperElement, className: "highlight-marker"});

**Comment by dbrnz** [comment]
Works for me, but the marker only shows when nerves are displayed.

<img width="389" alt="Screenshot 2024-02-29 at 9 08 09 AM" src="https://github.com/AnatomicMaps/flatmap-viewer/assets/239220/e67fc29e-719b-4c56-9e0f-947138fafa5b">

**Comment by dbrnz** [comment]
BTW is the return value of `addMarker()` checked? It will be `-1` if the map doesn't contain the anatomical entity.
